language: rust
cache: cargo
os:
    - windows
    - linux
    - osx

jobs:
  include:
    - name: Nightly
      env: TRAVIS_RUST_VERSION=nightly
    - name: Stable
      env: TRAVIS_RUST_VERSION=stable

before_script:
    - |
      curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION --profile=minimal -y &&
      export PATH=$PATH:$HOME/.cargo/bin &&
      travis_wait rustup component add rustfmt &&
      travis_wait rustup component add clippy

script:
    - |
      cargo test --all
      cargo doc --no-deps
      cargo clippy --all --tests -- --deny clippy::all
      cargo fmt -- --check
