[package]
name = "pyo3-log"
version = "0.1.0"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# It's OK to ask for std on log, because pyo3 needs it too.
log = { version = "~0.4", default-features = false, features = ["std"] }
pyo3 = { version = "~0.11", default-features = false, features = ["macros"] }
